# Generated by Django 5.0 on 2024-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_url',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
