# Generated by Django 5.0 on 2024-01-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_url',
        ),
    ]
