# Generated by Django 5.0 on 2024-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_page_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_url',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
