# Generated by Django 5.0 on 2024-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='en_tts_url',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='ko_tts_url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
