# Generated by Django 5.0 on 2024-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_en_tts_url_page_ko_tts_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
